paths:
  datasets:
    datasets_path: "./dat_vs_rag/artifacts/datasets"
    natural_questions_path: "./dat_vs_rag/artifacts/datasets/natural_questions_300.jsonl"
  chroma_db: 
    chroma_db_path: "./dat_vs_rag/artifacts/chroma_db"
    chroma_sqlite_path: "./dat_vs_rag/artifacts/chroma_db/chroma.sqlite3"
  models:
    models_path: "./dat_vs_rag/artifacts/models"
    bm25_params_path: "./dat_vs_rag/artifacts/models/bm25_param.json"
    ModernBert_path:  "./dat_vs_rag/artifacts/models/ModernBert"


model:
  name: "nickprock/ModernBERT-base-sts"

